{% set version = '0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-diffr
  version: {{ version|replace("-", "_") }}

source:
  fn: diffr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/diffr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/diffr/diffr_{{ version }}.tar.gz

  sha256: e82ec76b4eadee8ec682f83a8a9d3ffe6309fc31e6c66db573d6e7f8fdb5bc79

build:
  noarch: generic
  number: 1002

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmlwidgets

  run:
    - r-base
    - r-htmlwidgets

test:
  commands:
    - $R -e "library('diffr')"  # [not win]
    - "\"%R%\" -e \"library('diffr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=diffr
  license: GPL-2
  summary: An R interface to the 'codediff' JavaScript library (a copy of which is included in
    the package, see <https
  license_family: GPL2
extra:
   recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - Johanneskoester
    - Bgruening
    - Daler
    - Jdblischak
