appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: g8rN4/Ly6zViKJfC9Fjwjvey7LkyaIShdEFJPfE3hvFjEdNbzimIx9j3G6YWZirx7kNDiziHGQcHuyKywddvG0D4BTwDFlHHizmPLNy867egV3GygXia5CYkIzFuYeaLdooP+OPp22TBNaQKIAXADujf6IV4N+/eRH3AvLHlMg2UBUrVhqTExELdvhBS5rVuESAGrYWLrfyGpfEFFizrSUdgg+SJoEutdWfN2bSRQHyylj7Pk2OZX0rIp/TvYvN/Nq6vTn04smNnvuZz4JxbjkqVBKCSrdYOPFa3jGPSooYsKrttrwHUyGSxlQ+1zGP94uoXdBqk4zT3dyVtX7apxodAEeNDclJvGRLAEU1rJI9dJc0UyjPbtINHTEmmzkMFOdMzF/f8KgEiUEGAQX2hVvrjdwUN1fhTg2IsqJpqpKErzYjYclrNLYpBKr5sRIeXtJj7v9NzFIj97jCwB3vuvVrxRgst2eHcw7fmkSiC7QcrQdRHa+JDQpxPHQXOsqAKg/WtQBayBTSO+sD86cOKBeF2kM5K1xYH+Wcujc/iZx5Em47uzukrdxY18Xqnbobsy/29vjDNK2Nv1qbtZf6xXrdGLgK83m5JSzcRb+UO6g/Ejnvv7UbQ9UtKv43yy7PjuMmTFgmD4w2bVWQiX1JB1z+pc6CMQuRgoUtU1jPHZLc=}
