travis:
  secure:
    BINSTAR_TOKEN: Wo5e6L1y1e/shm1WhBWVgGyJvEcci6werdi/RwkC5q3hxQOxmESszJYN/WPyPdH2fTG9g1tHAGQi1K0C/fvw7eoNOY/Yyw/RETXOIw1Tizmch8w8pJIxeo8KiO7QWCUMU8TFdktzG5KBkM6h32oGZgVRFqFcqm1KjJ8lAGi4vwA3i7FB88i8S1E6Nz0DeMywYQKWeajid1eydM87syJEuUBxo2DDlwkJAnCZIy3RXJb+ogu2BcCnges7yAWY3H76CQJ24PFdXWRa8bp7iHo42E1tcWT2imI4SaoRX3GwhUWBB91p85x4M4Y3Ygi78IVYjHeMBAaN1eaqt+EuSio0ugc9z0SyPm8d3tCHDtJd9oRMdlLpqJE4knkcpadvwwNVDrQWHw8YTXIJiBvP/ZZEnv0sLWDhXVHGLTFJ/BIt2/0aJzdCWIbxS96gUQxG9pUe84yIl/tirqYpDXyZ6pe0DXMkdEPmIJOBBdJzLstwQTOCZAyrZ8jU65fuaQY6M8nutcBQS/MWqqqL00690sLBJkUm5HfsErWFl5T/EpDWTTa3zabG3Lqxb4pnhfubU+F8zANif9XHT+qkgb4uS6X1jZVOWMtxf4pl7sZdA4qUOjwNPZy28kLs5HhWKT8GB5QNIik9K5o7+Uh/k8IkAhcQ+DVmS14nBRc4YLXMYLVGOrc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
